### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by SaritasTea** [hhu-propra1/time-tracker#17]
Wo wir ja jetzt eine tabellarische Anzeige eingefügt haben, sollten wir das dann nicht auch in der ReadMe reinschreiben, dass das jetzt möglich ist? 
Und in die readme noch reinschreiben, dass es einen "-help" Befehl gibt, so der Vollständigkeit halber?

**Comment by n2o** [comment]
Ja unbedingt :-) sowas vergisst man immer... 😬

**Comment by dragonempire96** [comment]
Klar wie ear der befehl für die ausgabe?

**Comment by SaritasTea** [comment]
`java -jar SHADOW_JAR_FILE_NAME.jar -h` für help
`java -jar SHADOW_JAR_FILE_NAME.jar -t` für eine Tabelle aller Einträge
