### ISSUE TITLE
Template für Issues und Pull Request hinzufügen

### ISSUE THREAD

**Issue by dragonempire96** [hhu-propra1/time-tracker#27]
Damit alles einheitlich ist und die Wahrscheinlichkeit für rückfragen minimiert wird (Issues) und alles was geändert wurde beschrieben wird (pull requests).

**Comment by n2o** [comment]
👍 guter Punkt

**Comment by dragonempire96** [comment]
akzeptieren wir Pull Requests auch ohne Issue?

**Comment by n2o** [comment]
Für Issues wurde mit #31 templates eingefügt. Fehlt noch einer für Pull Requests 👍

**Comment by n2o** [comment]
Hier stand mal eine gute Frage drin, hast du sie gelöscht?

**Comment by dragonempire96** [comment]
ja da sie in der readme bereits mir beantwortet wurde bzw Pull Request nur mit Issue oder auch ohne war die Frage
