### ISSUE TITLE
--track-start und --track-done für "automatisches" Tracking

### ISSUE THREAD

**Issue by sakla106** [hhu-propra1/time-tracker#37]
Vielleicht wäre ja ein Befehl --track-start <Projekt> , der sich durch einen Befehl --track-done <Beschreibung> abschließen lässt und dann automatisch einen Eintrag hinzufügt, mit dem Datum des Beginns und den Minuten, die zwischen start und done vergangen sind, ganz cool.

Bei Bedarf noch ein --track-pause und --track-unpause, womit man das Tracken auch pausieren kann. Aber das ist eher weniger wichtig denke ich :D

Das sähe dann in etwa so aus:
>[2022-06-10 10:00] java -jar tt.jar --track-start Propra1
>[2022-06-10 10:40] java -jar tt.jar --track-done "Neues Issue für time-tracker erstellt"

Diese Befehle sollten dann ein neues Event speichern, so als ob man diesen Befehl eingegeben hätte:
>java -jar tt.jar --add 2022-06-10,40,Propra1,"Neues Issue für time-tracker erstellt"

**Comment by sakla106** [comment]
Zusätzlich noch eine Art "commit" oder so (mir fällt leider auf die Schnelle kein guter Name ein), wo mit man einfach beispielsweise
>java -jar tt.jar --track-TBD "Aufgabe 1 erledigt"

verwenden kann, sodass man quasi Subziele erreichen und diese mit einer Beschreibung speichern kann, ohne wieder --track-start benutzen zu müssen.

Also dann in etwa so
>[2022-06-10 10:00] java -jar tt.jar --track-start Propra1
>[2022-06-10 10:40] java -jar tt.jar --track-TBD "Neues Issue für time-tracker erstellt"
>[2022-06-10 11:25] java -jar tt.jar --track-done "Issue erweitert"

wäre dann das selbe wie
>java -jar tt.jar --add 2022-06-10,40,Propra1,"Neues Issue für time-tracker erstellt"
>java -jar tt.jar --add 2022-06-10,45,Propra1,"Issue erweitert"

**Comment by n2o** [comment]
Glaube Subziele ist ein bisschen viel, aber ein `--start` und `--stop` fände ich cool!

**Comment by dragonempire96** [comment]
hat sich erledigt die frage
