### ISSUE TITLE
Summe eines bestimmten Kurses

### ISSUE THREAD

**Issue by dragonempire96** [hhu-propra1/time-tracker#6]
Ich finde es fehlt noch die Funktion das nicht alle Min summiert werden, sondern zb nur alle Min vom Kurs Propa1 summiert werden.

**Comment by n2o** [comment]
Stimmt, können wir einbauen :-)

**Comment by sakla106** [comment]
Willst du dich da selbst dransetzen, oder ist das ein Issue für alle? :D @dragonempire96

**Comment by n2o** [comment]
Kannst du gerne übernehmen 👍

**Comment by n2o** [comment]
Ach falsch gelesen, du hast den Autor des Issues angepingt. Warten wir auf @dragonempire96

**Comment by dragonempire96** [comment]
Würde gerne selber coden liege momentan aber im krankenhaus da ich heute operiert wurde nach dem ich angefahren wurde @n2o
